# Generated by Django 4.1.5 on 2023-04-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="balance",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                    ("N/A", "N/A"),
                    ("Success", "Success"),
                ],
                default="Success",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("Credited", "Credited"), ("Debited", "Debited")],
                default="Credited",
                max_length=20,
            ),
        ),
    ]
